// ClawPazar – Shared Mock Data
// Realistic Turkish listings and auctions for when backend is offline

import type { Listing, Auction } from './api';

// ============================================================
// MOCK LISTINGS
// ============================================================

export const mockListings: Listing[] = [
    {
        id: 'mock-1',
        vendor_id: 'v1',
        title: 'iPhone 15 Pro Max 256GB — Doğal Titanyum',
        description: 'Kutusunda, tüm aksesuarlar mevcut. AppleCare+ Ekim 2025\'e kadar geçerli. Ekranda ve kasada çizik yok. Face ID, kamera, batarya %97 sağlık.',
        price: 58000,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'like_new',
        city: 'İstanbul',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 342,
        favorite_count: 28,
        created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
        vendors: { store_name: 'TechPazar', avg_rating: 4.8, store_slug: 'techpazar' },
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-2',
        vendor_id: 'v2',
        title: 'MacBook Air M3 15" 16GB/512GB — Gece Yarısı',
        description: '2024 model, kutu açılmamış sıfır ürün. Apple Türkiye garantili. Faturası mevcuttur.',
        price: 45500,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'new',
        city: 'Ankara',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 189,
        favorite_count: 45,
        created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
        vendors: { store_name: 'MacStore TR', avg_rating: 4.9, store_slug: 'macstore-tr' },
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-3',
        vendor_id: 'v3',
        title: 'PlayStation 5 Slim + 2 DualSense + 3 Oyun',
        description: 'PS5 Slim dijital sürüm. Spider-Man 2, God of War Ragnarök, FC 25 dahil. 2 orijinal DualSense kol. Kutulu, faturalı.',
        price: 19500,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'like_new',
        city: 'İzmir',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 567,
        favorite_count: 72,
        created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-4',
        vendor_id: 'v4',
        title: 'Nike Air Jordan 1 Retro High OG — Chicago',
        description: 'Orijinal, StockX doğrulamalı. 42 numara. Hiç giyilmedi, sadece denendi. Kutu ve etiket mevcut.',
        price: 8500,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'moda',
        condition: 'new',
        city: 'İstanbul',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 234,
        favorite_count: 56,
        created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
        categories: { name_tr: 'Moda', slug: 'moda' },
    },
    {
        id: 'mock-5',
        vendor_id: 'v5',
        title: 'Samsung Galaxy S24 Ultra 512GB — Titanium Gray',
        description: 'Galaxy AI özellikleri aktif. S Pen dahil. Çizik yok, cam koruyucu ve kılıf ile kullanıldı. Batarya sağlığı mükemmel.',
        price: 42000,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'like_new',
        city: 'Bursa',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 156,
        favorite_count: 19,
        created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-6',
        vendor_id: 'v6',
        title: 'iPad Pro M4 13" 256GB WiFi + Apple Pencil Pro',
        description: 'OLED ekran, M4 çip. Apple Pencil Pro dahil. Magic Keyboard ayrıca satılık. Çizim ve tasarım için ideal.',
        price: 38900,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'like_new',
        city: 'Antalya',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 98,
        favorite_count: 15,
        created_at: new Date(Date.now() - 36 * 3600000).toISOString(),
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-7',
        vendor_id: 'v7',
        title: 'Dyson V15 Detect Absolute — Lazer Süpürge',
        description: 'Dyson V15 Detect, lazer toz algılama özellikli. Tüm başlıklar mevcut. 1 yıl kullanıldı, mükemmel durumda.',
        price: 14500,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'ev',
        condition: 'used',
        city: 'İstanbul',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 87,
        favorite_count: 12,
        created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
        categories: { name_tr: 'Ev & Yaşam', slug: 'ev' },
    },
    {
        id: 'mock-8',
        vendor_id: 'v8',
        title: 'Adidas Yeezy Boost 350 V2 — Zebra',
        description: 'Orijinal, 43 numara. 3-4 kez giyildi. Temiz durumda, kutu mevcut.',
        price: 5200,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'moda',
        condition: 'used',
        city: 'Ankara',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 145,
        favorite_count: 33,
        created_at: new Date(Date.now() - 72 * 3600000).toISOString(),
        categories: { name_tr: 'Moda', slug: 'moda' },
    },
    {
        id: 'mock-9',
        vendor_id: 'v9',
        title: 'Apple Watch Ultra 2 — Titanyum, 49mm',
        description: 'Alpine Loop kordon + Ocean Band dahil. GPS + Cellular. Ekranda çizik yok, titanyum kasa mükemmel durumda.',
        price: 22000,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'aksesuar',
        condition: 'like_new',
        city: 'İstanbul',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 210,
        favorite_count: 41,
        created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
        categories: { name_tr: 'Aksesuar', slug: 'aksesuar' },
    },
    {
        id: 'mock-10',
        vendor_id: 'v10',
        title: 'Sony WH-1000XM5 — Gürültü Engelleme Kulaklık',
        description: 'Siyah renk, kutulu. ANC performansı harika. 30 saat pil ömrü. USB-C şarj. 6 ay kullanıldı.',
        price: 6800,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'used',
        city: 'Konya',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 178,
        favorite_count: 22,
        created_at: new Date(Date.now() - 96 * 3600000).toISOString(),
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
    {
        id: 'mock-11',
        vendor_id: 'v11',
        title: 'Antika Osmanlı Kahve Fincanı Seti — 6lı',
        description: 'El yapımı, altın yaldızlı. Koleksiyon değeri yüksek. 100+ yıllık orijinal parçalar. Sertifikalı.',
        price: 12000,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'koleksiyon',
        condition: 'used',
        city: 'Trabzon',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 67,
        favorite_count: 18,
        created_at: new Date(Date.now() - 120 * 3600000).toISOString(),
        categories: { name_tr: 'Koleksiyon', slug: 'koleksiyon' },
    },
    {
        id: 'mock-12',
        vendor_id: 'v12',
        title: 'DJI Mini 4 Pro Fly More Combo — Drone',
        description: '4K/60fps HDR video, 48MP fotoğraf. 3 batarya, şarj hub, çanta dahil. 10 uçuş yapıldı. Garanti devam ediyor.',
        price: 27500,
        currency: 'TRY',
        images: [],
        thumbnail_url: '',
        category_id: 'elektronik',
        condition: 'like_new',
        city: 'İstanbul',
        status: 'active',
        content_source: 'user',
        requires_human_review: false,
        view_count: 312,
        favorite_count: 64,
        created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
        categories: { name_tr: 'Elektronik', slug: 'elektronik' },
    },
];

// ============================================================
// MOCK AUCTIONS
// ============================================================

export const mockAuctions: Auction[] = [
    {
        id: 'auction-1',
        listing_id: 'mock-2',
        starting_price: 35000,
        current_price: 45200,
        reserve_price: 42000,
        min_bid_increment: 500,
        bid_count: 12,
        highest_bidder_id: 'u5',
        status: 'active',
        starts_at: new Date(Date.now() - 3600000).toISOString(),
        ends_at: new Date(Date.now() + 2 * 3600000 + 14 * 60000).toISOString(),
        listings: { title: 'MacBook Pro M3 14"', thumbnail_url: '', price: 55000 },
    },
    {
        id: 'auction-2',
        listing_id: 'mock-11',
        starting_price: 2000,
        current_price: 3800,
        reserve_price: 5000,
        min_bid_increment: 200,
        bid_count: 7,
        highest_bidder_id: 'u3',
        status: 'active',
        starts_at: new Date(Date.now() - 7200000).toISOString(),
        ends_at: new Date(Date.now() + 45 * 60000).toISOString(),
        listings: { title: 'Antika Osmanlı Kahve Fincanı Seti', thumbnail_url: '', price: 12000 },
    },
    {
        id: 'auction-3',
        listing_id: 'mock-3',
        starting_price: 500,
        current_price: 1200,
        reserve_price: 2000,
        min_bid_increment: 100,
        bid_count: 23,
        highest_bidder_id: 'u8',
        status: 'active',
        starts_at: new Date(Date.now() - 10800000).toISOString(),
        ends_at: new Date(Date.now() + 5 * 60000).toISOString(),
        listings: { title: 'Koleksiyon Pokémon Kart Seti', thumbnail_url: '', price: 3000 },
    },
    {
        id: 'auction-4',
        listing_id: 'mock-9',
        starting_price: 15000,
        current_price: 19800,
        reserve_price: 20000,
        min_bid_increment: 500,
        bid_count: 9,
        highest_bidder_id: 'u2',
        status: 'active',
        starts_at: new Date(Date.now() - 1800000).toISOString(),
        ends_at: new Date(Date.now() + 4 * 3600000).toISOString(),
        listings: { title: 'Apple Watch Ultra 2 — Titanyum', thumbnail_url: '', price: 22000 },
    },
];

// ============================================================
// HELPERS
// ============================================================

export function getMockListing(id: string): Listing | undefined {
    return mockListings.find((l) => l.id === id);
}

export function filterListings(opts: {
    category?: string;
    search?: string;
}): Listing[] {
    let results = [...mockListings];
    if (opts.category && opts.category !== 'all') {
        results = results.filter((l) => l.category_id === opts.category);
    }
    if (opts.search) {
        const q = opts.search.toLowerCase();
        results = results.filter((l) =>
            l.title.toLowerCase().includes(q) ||
            l.description.toLowerCase().includes(q) ||
            l.city.toLowerCase().includes(q)
        );
    }
    return results;
}
